### ISSUE TITLE
Не отображается поле content для перевода

### ISSUE THREAD

**Issue by Ibochkarev** [nizart91/localizator#4]
Если не установлен визуальный редактор - то поле для перевода отображается следующим образом:
![image](https://user-images.githubusercontent.com/2138260/58367171-e1b3e680-7efd-11e9-83ca-46e50a91ebb3.png)

Если устанавливаем редактор, например TinyMCE - все **ок:**
![image](https://user-images.githubusercontent.com/2138260/58367181-fb552e00-7efd-11e9-99d7-f2410ca234c2.png)

**Comment by nizart91** [comment]
fixed
