### ISSUE TITLE
PHP warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by lexsmil** [nizart91/localizator#7]
core/components/localizator/model/localizator/localizator.class.php : 98) PHP warning: Invalid argument supplied for foreach()

https://github.com/nizart91/localizator/blob/390a6c423d912ee782d5904fcde2eaad1125e702/core/components/localizator/model/localizator/localizator.class.php#L98

**FIX:**
Line 96:
`foreach ((array)$tabs as $tabid => $subtab) {`

**Comment by nizart91** [comment]
fixed
