### ISSUE TITLE
Не сохраняется состояние отметки чекбокса

### ISSUE THREAD

**Issue by Ibochkarev** [nizart91/localizator#9]
Если создать ТВ с типом флажки:

![image](https://user-images.githubusercontent.com/2138260/66423798-34fe7f80-ea2e-11e9-9ab7-062d5ca71212.png)

Применить к шаблону и отметить его в Локализации все ОК, но когда ты хочешь снять данный чекбокс и сохранить - то информация не сохраняется.

Отметка не снимается.

Данный баг обнаружен на 2-х сайтах.

**Comment by nizart91** [comment]
fixed
